version: '3'

services:
  reverse-proxy:
    image: traefik:2.3
    container_name: ${APP_NAME}_traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - .docker/traefik/certificates.yml:/etc/traefik/certificates.yml
      - .docker/certs:/certs
    expose:
      - 8080
    networks:
      - kickoff-proxy
    ports:
      - 80:80
      - 443:443
    restart: always


networks:
  kickoff-proxy:
    external:
      name: kickoff-proxy
